name: taskilo
description: 'Taskilo - Your Service Marketplace'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.6.2
  flutter_local_notifications: ^18.0.1

  # Payment (via Web API / WebView)
  # Stripe removed - payments handled via Revolut API

  # Location & Maps
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  google_places_autocomplete_text_field: ^0.0.3
  google_polyline_algorithm: ^3.1.0

  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.7.0
  socket_io_client: ^3.0.1
  flutter_dotenv: ^5.1.0

  # UI Components & Utils
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  # Video Conferencing - WebRTC
  flutter_webrtc: ^1.2.1
  firebase_database: ^11.0.9

  # Time & Date
  intl: ^0.20.0
  timeago: ^3.7.0
  table_calendar: ^3.0.9
  add_2_calendar: ^3.0.1

  # Storage & Preferences
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Animation & Visuals
  lottie: ^3.1.2
  shimmer: ^3.0.0

  # Development & Debug
  logger: ^2.4.0
  google_sign_in: 6.2.1
  syncfusion_flutter_pdfviewer: ^31.1.19
  device_info_plus: ^11.5.0
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/taskilo_logo.jpg'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/images/taskilo_logo.jpg'
    background_color: '#14ad9f'
    theme_color: '#14ad9f'
  windows:
    generate: true
    image_path: 'assets/images/taskilo_logo.jpg'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/taskilo_logo.jpg'

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
